#
# usage:  make         - compile asmedit executable
#         make clean   - remove binaries
#         make install - install files
#         make release - create release file
#
include ../Makefile.Common
#
all:	$(TARGETS)
#
$(OBJS):
#
clean:
	-rm -f $(TARGETS) $(OBJS)
#
